# Generated by Django 5.0.6 on 2024-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_registrationform_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='course',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='state',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
